### ISSUE TITLE
Engine Backend

### ISSUE THREAD

**Issue by jrdzha** [Luminarys/Nishikaku#1]
Hi this is Kaylee's friend

I have some experience with Java cross platform game engines (lets not argue about the viability of Java game development here lol)
Look up Kingdom Dash on iOS/Android to see my work

My question for this engine is why are you guys writing everything from scratch? Why not build an engine by writing bindings to other libraries/frameworks like OpenGL for graphics or Box2D for physics? OpenGL is the work of thousands of GPU software engineers and Box2D is the work of someone with industry experience in implementing physics engines? It make much more sense to use the expertise of others to create a game engine rather than starting everything from scratch.. 

Jared

**Comment by ddevault** [comment]
Hi this is Drew

This uses OpenGL and doesn't do physics..

Drew

**Comment by Luminarys** [comment]
My goal with this game was to learn about the process of game development in general, from the ground up(for the most part), not to learn some arbitrary API which can do something like physics or graphics, although inevitably there is a bit of that. This game is not a AAA nor do I expect it to be anything near that, just a project I'm developing for fun, and as such I see little need to rely on external libraries. 

Funnily enough though, previously for physics I was in fact using a generic library(ncollide). Because bullet hells have very specific needs for physics checking the library actually performed quite poorly compared to an extremely simple engine I implemented myself that was optimized for the types of collision checking I needed to actually do. Just goes to show that sometimes the best solution is to roll your own, though that's obviously not always true.

You also seem to have made an incorrect comment about the engine, specifically wrt to OpenGL. I'm using OpenGL to get cross platform graphics support, I'm not sure where you got the idea otherwise.

I hope that clears things up and one last question, who's Kaylee?
